CREATE TABLE USERS(
	USER_ID VARCHAR(32) COLLATE LATIN1_GENERAL_CI NOT NULL,
	PASSWORD TEXT COLLATE LATIN1_BIN NOT NULL,
	CONSTRAINT PRIMARY KEY(USER_ID)
);
CREATE TABLE PHOTO(
	PHOTO_ID VARCHAR(38) COLLATE LATIN1_BIN NOT NULL,
	TITLE VARCHAR(500) COLLATE UTF8_BIN,
	PATH TEXT COLLATE UTF8_BIN NOT NULL,
	OWNER VARCHAR(32) COLLATE LATIN1_GENERAL_CI NOT NULL,
	FILE_SIZE INT UNSIGNED NOT NULL,
	PHOTO_LENGTH INT UNSIGNED NOT NULL,
	PHOTO_HEIGHT INT UNSIGNED NOT NULL,
	DESCRIPTION TEXT COLLATE UTF8_BIN,
	CONSTRAINT PRIMARY KEY(PHOTO_ID),
	CONSTRAINT FOREIGN KEY(OWNER) REFERENCES USERS(USER_ID)
);
CREATE TABLE THUMBNAIL(
	THUMBNAIL_ID VARCHAR(64) NOT NULL,
	PHOTO_ID VARCHAR(38) COLLATE LATIN1_BIN NOT NULL,
	PATH TEXT COLLATE UTF8_BIN NOT NULL,
	FILE_SIZE INT UNSIGNED NOT NULL,
	PHOTO_LENGTH INT UNSIGNED NOT NULL,
	PHOTO_HEIGHT INT UNSIGNED NOT NULL,
	CONSTRAINT PRIMARY KEY(THUMBNAIL_ID),
	CONSTRAINT UNIQUE INDEX (PHOTO_ID, PHOTO_LENGTH),
	CONSTRAINT FOREIGN KEY (PHOTO_ID) REFERENCES PHOTO(PHOTO_ID)
);
CREATE TABLE ALBUM(
	ALBUM_ID VARCHAR(32) COLLATE latin1_general_ci NOT NULL,
	ALBUM_NAME VARCHAR(500) COLLATE utf8_bin NOT NULL,
	OWNER VARCHAR(32) COLLATE LATIN1_GENERAL_CI NOT NULL,
	MAIN_PICTURE VARCHAR(38) COLLATE LATIN1_BIN,
	DESCRIPTION TEXT COLLATE UTF8_BIN,
	CONSTRAINT PRIMARY KEY(ALBUM_ID),
	CONSTRAINT FOREIGN KEY(OWNER) REFERENCES USERS(USER_ID),
	CONSTRAINT FOREIGN KEY(MAIN_PICTURE) REFERENCES PHOTO(PHOTO_ID)
);
CREATE TABLE ALBUM_PHOTO(
	ALBUM_ID VARCHAR(32) COLLATE latin1_general_ci NOT NULL,
	SEQ_NO INT UNSIGNED NOT NULL,
	PHOTO_ID VARCHAR(38) COLLATE LATIN1_BIN NOT NULL,
	CONSTRAINT PRIMARY KEY(ALBUM_ID, SEQ_NO),
	CONSTRAINT FOREIGN KEY(ALBUM_ID) REFERENCES ALBUM(ALBUM_ID),
	CONSTRAINT FOREIGN KEY(PHOTO_ID) REFERENCES PHOTO(PHOTO_ID)
);
CREATE TABLE PHOTO_EXIF(
	PHOTO_ID VARCHAR(38) COLLATE LATIN1_BIN NOT NULL,
	EXIF_KEY VARCHAR(255) COLLATE LATIN1_GENERAL_CI NOT NULL,
	EXIF_VALUE TEXT COLLATE UTF8_BIN,
	CONSTRAINT PRIMARY KEY(PHOTO_ID, EXIF_KEY),
	CONSTRAINT FOREIGN KEY(PHOTO_ID) REFERENCES PHOTO(PHOTO_ID)
);
